export function usageText(): string {
  return [
    "PageSnap - walk the app, auto-record steps, checkpoint YAML for LLM test generation.",
    "Not a click-to-spec.ts emitter. Capture is never automatic on navigation.",
    "",
    "Demo",
    "  npm install",
    "  npx playwright install chromium",
    "  npm run capture -- https://app.com",
    "  Then walk the app. Ctrl+M (checkpoint), Ctrl+Shift+M (note), Ctrl+Q (end).",
    "  Clicks, fills, checks, selects, and navigations are recorded automatically.",
    "",
    "  npm run capture -- https://example.com --framework=playwright --goal='Register a user'",
    "  npm run capture -- --help",
    "",
    "Usage",
    "  npm run capture -- <url> [options]",
    "  npm run capture -- --connect=<cdp-url>   (optional url if a tab is already open)",
    "",
    "Hotkeys",
    "  Ctrl+M / Cmd+M              Checkpoint snapshot (toolbar: Capture)",
    "  Ctrl+Shift+M / Cmd+Shift+M  Checkpoint with a note",
    "  Ctrl+Q / Cmd+Q              End session",
    "  Never Ctrl+K",
    "",
    "Options  (flags beat capture.config.properties)",
    "  --goal=<text>               Session goal copied into PROMPT.md",
    "  --config=<file>             Extra properties file",
    "  --output=<dir>              Output root (default: pageSnapshots)",
    "  --flat                      Write into output root (no session subfolder)",
    "  --lean                      Token-lean YAML (DEFAULT): 1 locator, no hints, strip /url:",
    "  --full                      Verbose dump: 2 locators, hints, urls, maxTableRows>=5",
    "  --hints                     Append framework hint footer (off by default)",
    "  --no-hints                  Do not append hint footer",
    "  --no-urls                   Strip /url: lines from YAML (DEFAULT)",
    "  --urls                      Keep /url: dumps",
    "  --aria                      Also write NN_<host>_aria.yml via Playwright. Off by default",
    "  --load-cookies=<file>       Load cookies JSON before the walk",
    "  --save-cookies=<file>       Save cookies JSON on exit",
    "  --load-storage=<file>       Load Playwright storageState",
    "  --save-storage=<file>       Save Playwright storageState on exit",
    "  --max-table-rows=<n>        Table body rows to dump (lean default 3, --full 5)",
    "  --framework=<name>          playwright | selenium | cypress | webdriverio | testcafe | other",
    "  --style=<name>              Copied to PROMPT (default pageobject)",
    "  --waits=<name>              Copied to PROMPT (default web-first)",
    "  --no-redact                 Leave password values and emails unmasked",
    "  --no-diff                   Skip NN_diff.md between checkpoints",
    "  --headless                  Launch headless (manual capture is harder)",
    "  --timezone=<iana>           Session-folder timestamps (default America/New_York)",
    "  --toolbar-position=left|middle|right  Floating toolbar dock",
    "  --connect=<url>             Attach over the DevTools debugging port (alias: cdp)",
    "  --cdp=<url>                 Same as connect. URL optional if a tab is already open.",
    "",
    "Output (pageSnapshots/session-<ts>/)",
    "  steps.md                    Every goto/click/fill/check/select/nav + snapshot checkpoints",
    "  flow.md                     Checkpoint narrative (notes, YAML files)",
    "  NN_<host>.yaml              Lean ARIA-inspired tree + one live-verified locator",
    "  NN_diff.md                  What changed vs previous checkpoint",
    "  PROMPT.md  Reading-Snapshots.md",
    "",
    "Lean is the product. Use --full only when you need the verbose dump.",
    ""
  ].join("\n");
}

export function printUsage(): string {
  const text = usageText();
  console.log(text);
  return text;
}
